export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_BASKET = "ADD_BASKET"
export const DEL_BASKET = "DEL_BASKET"
export const GET_PRODUCT = "GET_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const SAVE_PRODUCT = "SAVE_PRODUCT"